import { useReducer, useEffect } from "react";
import Head from "next/head";
import TimeDisplay from "../components/TimeDisplay";
import TimerReducer from "../reducers/TimerReducer";

export default function Home() {
  const [state, dispatch] = useReducer(TimerReducer, {
    currentState: "IDLE",
    timeElapsed: 0,
    timerStartTime: 0,
  });

  useEffect(() => {
    if (state.currentState === "RUNNING") {
      const intervalRef = setInterval(() => {
        dispatch({
          type: "TICK",
        });
      }, 1);
      return () => clearInterval(intervalRef);
    }
  }, [state]);

  return (
    <div className="body">
      <Head>
        <title>Pomodoro Timer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1 className="title-2">Pomodoro Timer</h1>
      <button onClick={() => dispatch({ type: "START" })}>START</button>
      <button onClick={() => dispatch({ type: "PAUSE" })}>PAUSE</button>
      <button onClick={() => dispatch({ type: "RESET" })}>RESET</button>
      <TimeDisplay miliseconds={state.timeElapsed} />
      <p style={{ color: "var(--fc-500)" }}>
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Cupiditate
        laudantium qui perferendis tempore magnam minima distinctio nobis
        placeat asperiores hic voluptatum similique, soluta quisquam! Alias
        consequatur minima est dolores dolore! Voluptatum ratione autem quisquam
        quaerat deserunt expedita mollitia quos eum aliquam, eos earum
        dignissimos, velit sit laboriosam accusantium quis? Architecto commodi
        alias quo corrupti quisquam quibusdam eveniet beatae nam voluptatum.
        Officiis inventore numquam ipsum blanditiis? Fuga aspernatur minus
        molestias ipsam beatae labore eligendi delectus nostrum dolorem, at et
        voluptates esse itaque inventore explicabo ipsum temporibus obcaecati
        eius placeat voluptatum excepturi? Repudiandae molestias in quaerat
        placeat consequuntur, aliquid vitae perspiciatis esse soluta ipsa
        nostrum distinctio quasi velit officia, eveniet itaque molestiae earum
        at ipsum? Facere officia doloribus pariatur, vel minima id. Id ipsam
        accusamus architecto deleniti adipisci, tempora quia quae eum alias sint
        illo quos et quibusdam! Ipsum, cupiditate. Totam voluptatem vel debitis
        sit quam odio, officia illum molestias officiis dolores!
      </p>
    </div>
  );
}
