import { useReducer, useEffect } from "react";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import DisplayTime from "../components/DisplayTime";

//states: IDLE, RUNNING, PAUSED
//action.types: "START", "PAUSE", "RESET"

const reducer = (state, action) => {
  switch (state.currentState) {
    case "IDLE":
      if (action.type === "START") {
        const newState = { ...state };
        newState.currentState = "RUNNING";
        return newState;
      }
      console.error(`state = ${state}, action = ${action}`);
      break;
    case "RUNNING":
      if (action.type === "PAUSE") {
        return {
          ...state,
          currentState: "PAUSED",
        };
      }
      if (action.type === "RESET") {
        return {
          ...state,
          currentState: "IDLE",
          currentTime: 0,
        };
      }
      if (action.type === "TICK") {
        const newState = { ...state };
        newState.currentTime++;
        return newState;
      }
      break;
    case "PAUSED":
      if (action.type === "START") {
        return {
          ...state,
          currentState: "RUNNING",
        };
      }
      if (action.type === "RESET") {
        return {
          ...state,
          currentState: "IDLE",
          currentTime: 0,
        };
      }
      break;
    default:
      console.error("something went wrong in reducer");
  }
};

export default function Home() {
  const [state, dispatch] = useReducer(reducer, {
    currentState: "IDLE",
    currentTime: 0,
  });

  useEffect(() => {
    console.log("state.currentState", state.currentState);

    if (state.currentState === "RUNNING") {
      console.log("INSIDE RUNNING");
      const intervalRef = setInterval(() => {
        console.log("tick");
        dispatch({
          type: "TICK",
        });
      }, 1);
      return () => clearTimeout(intervalRef);
    }
  }, [state]);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>Pomodoro Timer</h1>
      <button
        onClick={() =>
          dispatch({
            type: "START",
          })
        }>
        START
      </button>
      <button onClick={() => dispatch({ type: "PAUSE" })}>PAUSE</button>
      <button onClick={() => dispatch({ type: "RESET" })}>RESET</button>
      <DisplayTime miliseconds={state.currentTime} />
    </div>
  );
}
